import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Header
    welcome: "Welcome!",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    language: "Language",
    // Search & filter
    search: "Search...",
    filterBy: "Filter by",
    allCategories: "All",
    sortBy: "Sort by",
    sortNameAsc: "Name (A–Z)",
    sortPriceAsc: "Price: Low to High",
    sortPriceDesc: "Price: High to Low",
    sortRatingDesc: "Top Rated",
    // Catalog
    products: "Products",
    noResults: "No products found.",
    // Product
    addToCart: "Add to Cart",
    addedToCart: "Added to cart",
    addToFavorites: "Add to favorites",
    removeFromFavorites: "Remove from favorites",
    addedToFavorites: "Added to favorites",
    removedFromFavorites: "Removed from favorites",
    description: "Description",
    off: "off",
    // Comparison
    compare: "Compare Selected",
    comparisonResult: "Comparison Result",
    savings: "If you buy the cheapest product, you would save",
    selectTwo: "Please select at least 2 products to compare.",
    close: "Close",
    // Cart
    cart: "Cart",
    emptyCart: "Your cart is empty.",
    continueShopping: "Continue Shopping",
    removeFromCart: "Remove",
    subtotal: "Subtotal",
    total: "Total",
    checkout: "Proceed to Checkout",
    qty: "Qty",
    // Misc
    back: "Back",
    notFound: "Product not found.",
    footerRights: "All rights reserved.",
    footerBuiltWith: "Built with",
    favorites: "Favorites",
    noFavorites: "No favorites yet. Heart a product to save it here.",
  },
  fr: {
    welcome: "Bienvenue !",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    language: "Langue",
    search: "Rechercher...",
    filterBy: "Filtrer par",
    allCategories: "Tout",
    sortBy: "Trier par",
    sortNameAsc: "Nom (A–Z)",
    sortPriceAsc: "Prix : croissant",
    sortPriceDesc: "Prix : décroissant",
    sortRatingDesc: "Mieux notés",
    products: "Produits",
    noResults: "Aucun produit trouvé.",
    addToCart: "Ajouter au panier",
    addedToCart: "Ajouté au panier",
    addToFavorites: "Ajouter aux favoris",
    removeFromFavorites: "Retirer des favoris",
    addedToFavorites: "Ajouté aux favoris",
    removedFromFavorites: "Retiré des favoris",
    description: "Description",
    off: "de réduction",
    compare: "Comparer la sélection",
    comparisonResult: "Résultat de la comparaison",
    savings: "En achetant le produit le moins cher, vous économiseriez",
    selectTwo: "Veuillez sélectionner au moins 2 produits à comparer.",
    close: "Fermer",
    cart: "Panier",
    emptyCart: "Votre panier est vide.",
    continueShopping: "Continuer les achats",
    removeFromCart: "Retirer",
    subtotal: "Sous-total",
    total: "Total",
    checkout: "Passer la commande",
    checkoutSoon: "Paiement bientôt disponible !",
    qty: "Qté",
    back: "Retour",
    notFound: "Produit introuvable.",
    footerRights: "Tous droits réservés.",
    footerBuiltWith: "Créé avec",
    favorites: "Favoris",
    noFavorites: "Aucun favori. Cliquez sur le cœur pour sauvegarder des produits.",
  },
  nl: {
    welcome: "Welkom!",
    lightMode: "Lichte modus",
    darkMode: "Donkere modus",
    language: "Taal",
    search: "Zoeken...",
    filterBy: "Filteren op",
    allCategories: "Alles",
    sortBy: "Sorteren op",
    sortNameAsc: "Naam (A–Z)",
    sortPriceAsc: "Prijs: laag naar hoog",
    sortPriceDesc: "Prijs: hoog naar laag",
    sortRatingDesc: "Best beoordeeld",
    products: "Producten",
    noResults: "Geen producten gevonden.",
    addToCart: "In winkelwagen",
    addedToCart: "Toegevoegd aan winkelwagen",
    addToFavorites: "Toevoegen aan favorieten",
    removeFromFavorites: "Verwijderen uit favorieten",
    addedToFavorites: "Toegevoegd aan favorieten",
    removedFromFavorites: "Verwijderd uit favorieten",
    description: "Beschrijving",
    off: "korting",
    compare: "Vergelijk selectie",
    comparisonResult: "Vergelijkingsresultaat",
    savings: "Als u het goedkoopste product koopt, bespaart u",
    selectTwo: "Selecteer minimaal 2 producten om te vergelijken.",
    close: "Sluiten",
    cart: "Winkelwagen",
    emptyCart: "Uw winkelwagen is leeg.",
    continueShopping: "Verder winkelen",
    removeFromCart: "Verwijderen",
    subtotal: "Subtotaal",
    total: "Totaal",
    checkout: "Afrekenen",
    checkoutSoon: "Afrekenen binnenkort beschikbaar!",
    qty: "Aant",
    back: "Terug",
    notFound: "Product niet gevonden.",
    footerRights: "Alle rechten voorbehouden.",
    footerBuiltWith: "Gebouwd met",
    favorites: "Favorieten",
    noFavorites: "Nog geen favorieten. Klik op het hartje om producten op te slaan.",
  },
  de: {
    welcome: "Willkommen!",
    lightMode: "Heller Modus",
    darkMode: "Dunkler Modus",
    language: "Sprache",
    search: "Suchen...",
    filterBy: "Filtern nach",
    allCategories: "Alle",
    sortBy: "Sortieren nach",
    sortNameAsc: "Name (A–Z)",
    sortPriceAsc: "Preis: aufsteigend",
    sortPriceDesc: "Preis: absteigend",
    sortRatingDesc: "Bestbewertet",
    products: "Produkte",
    noResults: "Keine Produkte gefunden.",
    addToCart: "In den Warenkorb",
    addedToCart: "Zum Warenkorb hinzugefügt",
    addToFavorites: "Zu Favoriten hinzufügen",
    removeFromFavorites: "Aus Favoriten entfernen",
    addedToFavorites: "Zu Favoriten hinzugefügt",
    removedFromFavorites: "Aus Favoriten entfernt",
    description: "Beschreibung",
    off: "Rabatt",
    compare: "Auswahl vergleichen",
    comparisonResult: "Vergleichsergebnis",
    savings: "Wenn Sie das günstigste Produkt kaufen, sparen Sie",
    selectTwo: "Bitte wählen Sie mindestens 2 Produkte zum Vergleichen.",
    close: "Schließen",
    cart: "Warenkorb",
    emptyCart: "Ihr Warenkorb ist leer.",
    continueShopping: "Weiter einkaufen",
    removeFromCart: "Entfernen",
    subtotal: "Zwischensumme",
    total: "Gesamt",
    checkout: "Zur Kasse",
    checkoutSoon: "Kasse demnächst verfügbar!",
    qty: "Menge",
    back: "Zurück",
    notFound: "Produkt nicht gefunden.",
    footerRights: "Alle Rechte vorbehalten.",
    footerBuiltWith: "Erstellt mit",
    favorites: "Favoriten",
    noFavorites: "Noch keine Favoriten. Klicke auf das Herz, um Produkte zu speichern.",
  },
  sv: {
    welcome: "Välkommen!",
    lightMode: "Ljust läge",
    darkMode: "Mörkt läge",
    language: "Språk",
    search: "Sök...",
    filterBy: "Filtrera efter",
    allCategories: "Alla",
    sortBy: "Sortera efter",
    sortNameAsc: "Namn (A–Ö)",
    sortPriceAsc: "Pris: lågt till högt",
    sortPriceDesc: "Pris: högt till lågt",
    sortRatingDesc: "Bäst betyg",
    products: "Produkter",
    noResults: "Inga produkter hittades.",
    addToCart: "Lägg i kundvagn",
    addedToCart: "Tillagd i kundvagnen",
    addToFavorites: "Lägg till i favoriter",
    removeFromFavorites: "Ta bort från favoriter",
    addedToFavorites: "Tillagd i favoriter",
    removedFromFavorites: "Borttagen från favoriter",
    description: "Beskrivning",
    off: "rabatt",
    compare: "Jämför urval",
    comparisonResult: "Jämförelseresultat",
    savings: "Om du köper den billigaste produkten sparar du",
    selectTwo: "Välj minst 2 produkter att jämföra.",
    close: "Stäng",
    cart: "Kundvagn",
    emptyCart: "Din kundvagn är tom.",
    continueShopping: "Fortsätt handla",
    removeFromCart: "Ta bort",
    subtotal: "Delsumma",
    total: "Totalt",
    checkout: "Till kassan",
    checkoutSoon: "Kassan kommer snart!",
    qty: "Ant",
    back: "Tillbaka",
    notFound: "Produkten hittades inte.",
    footerRights: "Alla rättigheter förbehållna.",
    footerBuiltWith: "Byggd med",
    favorites: "Favoriter",
    noFavorites: "Inga favoriter ännu. Klicka på hjärtat för att spara produkter.",
  },
};

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "nl", label: "Nederlands" },
  { code: "de", label: "Deutsch" },
  { code: "sv", label: "Svenska" },
];

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  const setLanguage = (code) => {
    setLang(code);
    localStorage.setItem("lang", code);
  };

  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
